#!/bin/sh

. config/options

if [ "$1" = generator ]; then
  cp -PR $ROOTFS/etc $INSTALL
  rm -rf $ROOTFS/etc
else
  rm -rf $INSTALL/etc
fi

cp -PR $ROOTFS/boot $INSTALL
$SCRIPTS/initramfs image
$SCRIPTS/squashfs
if [ "$TARGET_ARCH" = i386 -o "$TARGET_ARCH" = x86_64 ]; then
  $SCRIPTS/installdev syslinux
  cp -PR $ROOT/$TOOLCHAIN/boot $INSTALL/
  cp $ROOT/$TOOLCHAIN/loopdisk.zip $INSTALL/
  cp $ROOT/$TOOLCHAIN/unzip.exe $INSTALL/
  $SCRIPTS/installdev grub-efi
  cp -PR $ROOT/$TOOLCHAIN/efi $INSTALL
elif [ "$TARGET_ARCH" = powerpc -o "$TARGET_ARCH" = powerpc64 ]; then
  $SCRIPTS/installdev yaboot
  cp -PR $ROOT/$TOOLCHAIN/boot $INSTALL/
fi

exit 0
